font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15.0
# cursor #7fb8d1
# cursor_text_color #FFFFFF
cursor_shape underline 
cursor_shape_unfocused underline
cursor_beam_thickness 0.8
cursor_underline_thickness 2.0
cursor_blink_interval 1 ease-in-out
cursor_stop_blinking_after 0
cursor_trail 3
cursor_trail_decay 0.2 0.4
cursor_trail_start_threshold 1

mouse_hide_wait -1
# url_color #e296ac
url_style dashed
open_url_with safari
url_prefixes file git http https kitty ssh
detect_urls yes
underline_hyperlinks always
strip_trailing_spaces always
select_by_word_characters @-./_~#
select_by_word_characters_forward
click_interval -1.0
focus_follows_mouse no
pointer_shape_when_grabbed arrow
default_pointer_shape beam

pointer_shape_when_dragging beam crosshair

enable_audio_bell no
visual_bell_duration 0.00
# visual_bell_color none
window_alert_on_bell yes

remember_window_size no
initial_window_width 1500
initial_window_height 900
placement_strategy center
# active_border_color #c77c98
# inactive_border_color #3e3a64
# bell_border_color #FFFFFF
# foreground #FFFFFF
# background #000000
background_tint 1
background_opacity 0.9
background_blur 1

# BEGIN_KITTY_THEME
# spaceduck
include current-theme.conf
# END_KITTY_THEME
